var dataModel = {
    istNo: 0,
    ICAO: 1,
    ad: 2,
    lon: 3,
    lat: 4,
    alt: 5,
    autoMan: 6,
    year: 7,
    month: 8,
    day: 9,
    hour: 10,
    temperature: 11,
    dewPoint: 12,
    cloudCoverObs: 13,
    cloudBottomObs: 14,
    cloudBottomEst: 15,
    cloudCoverSat: 16,
    cloudLowSat: 17,
    cloudMidSat: 18,
    cloudHiSat: 19,
    lighteningCount: 20,
    radarPPI: 21,
    cloudBottomRadar: 22,
    radarMaxTop: 23,
    radarMxValue: 24,
    cloudBottomInterpole: 25,
    windDirection: 26,
    windSpeed: 27,
    visibility:28,
    observation: 29
}